"""v86: Stronger view-count conditioning for sparse-view robustness.

This module augments the ray tokens produced by the v25 geometry-fusion block
with an *explicit view-count token* that is generated by a small MLP conditioned
on the number of active views.  It is designed to sit on top of the v85 random
view-dropout training recipe: v85 still drops whole views, but v86 replaces the
simple count embedding with a learned, nonlinear count-to-token mapping.

The module is identity at initialization: the final MLP layer and the count
embedding table are zero-initialized, and a gated residual path is initialized
near zero, so enabling the module does not change the model output at epoch 0.
"""

from __future__ import annotations

from typing import Optional

import torch
import torch.nn as nn


class ViewCountConditioningV86(nn.Module):
    """Explicit view-count token / MLP conditioning for sparse-view fusion.

    Parameters
    ----------
    d:
        Ray-token dimension.  The produced count token has the same dimension
        and is broadcast-added to every view/joint token.
    n_views:
        Maximum number of camera views (only used for ``max_views`` default).
    hidden:
        Hidden dimension of the count-to-token MLP.
    n_layers:
        Number of layers in the count-to-token MLP (>= 1).
    dropout:
        Dropout probability applied inside the MLP.
    max_views:
        Upper bound on the supported view count for the learned embedding table.
        If ``None``, defaults to ``n_views``.
    use_count_token:
        If True, generate an explicit count token and add it to the ray tokens.
        This is the only mode currently implemented; kept as a flag for future
        FiLM / appended-token variants.
    """

    def __init__(
        self,
        d: int = 128,
        n_views: int = 4,
        hidden: int = 64,
        n_layers: int = 2,
        dropout: float = 0.1,
        max_views: Optional[int] = None,
        use_count_token: bool = True,
    ) -> None:
        super().__init__()
        if not use_count_token:
            raise ValueError("v86 currently requires use_count_token=True")
        if n_layers < 1:
            raise ValueError(f"n_layers must be >= 1, got {n_layers}")

        self.d = d
        self.n_views = n_views
        self.hidden = hidden
        self.n_layers = n_layers
        self.max_views = max_views if max_views is not None else n_views
        self.use_count_token = use_count_token

        # Learnable embedding for each possible active-view count.
        self.count_embed = nn.Embedding(self.max_views + 1, hidden)
        nn.init.zeros_(self.count_embed.weight)

        # Count-to-token MLP.
        layers: list[nn.Module] = []
        for i in range(n_layers):
            is_last = i == n_layers - 1
            in_dim = hidden if i == 0 else hidden
            out_dim = d if is_last else hidden
            layers.append(nn.Linear(in_dim, out_dim))
            if not is_last:
                layers.append(nn.ReLU())
                if dropout > 0.0:
                    layers.append(nn.Dropout(dropout))
        self.mlp = nn.Sequential(*layers)

        # Gated residual path, initialized near identity.
        self.residual_logit = nn.Parameter(torch.tensor(-6.0))

        # Zero-initialize the final MLP layer so the count token starts at 0.
        final_linear = self.mlp[-1]
        assert isinstance(final_linear, nn.Linear)
        nn.init.zeros_(final_linear.weight)
        nn.init.zeros_(final_linear.bias)

    def forward(
        self,
        tokens: torch.Tensor,
        view_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """Add an explicit, MLP-conditioned view-count token to ``tokens``.

        Args:
            tokens: ``(B, T, V, J, d)`` ray tokens.
            view_mask: optional ``(B, T, V)`` bool mask.  ``True`` means the view
                is active.  If ``None``, all ``n_views`` views are assumed active.

        Returns:
            tokens: ``(B, T, V, J, d)`` with count conditioning added.
        """
        B, T, V, J, d = tokens.shape

        if view_mask is None:
            count = torch.full((B, T), V, dtype=torch.long, device=tokens.device)
        else:
            view_mask = view_mask.bool()
            count = view_mask.sum(dim=-1).long()  # (B, T)
        count = count.clamp(min=0, max=self.max_views)

        count_emb = self.count_embed(count)  # (B, T, hidden)
        count_token = self.mlp(count_emb)  # (B, T, d)

        gate = torch.sigmoid(self.residual_logit)
        return tokens + gate * count_token[:, :, None, None, :]


if __name__ == "__main__":
    B, T, V, J, d = 2, 4, 4, 17, 128
    tokens = torch.randn(B, T, V, J, d)
    view_mask = torch.ones(B, T, V, dtype=torch.bool)
    view_mask[:, :, :2] = False  # only 2 active views

    module = ViewCountConditioningV86(d=d, n_views=V, hidden=64, n_layers=2)
    out = module(tokens, view_mask)
    assert out.shape == tokens.shape
    # At init the output should be nearly identical to the input.
    assert torch.allclose(out, tokens, atol=1e-5)
    print("ViewCountConditioningV86 CPU smoke test passed")
