#!/usr/bin/env python3
"""Generate configs/splits/mix_true_gt_v2.yaml.

Split design (v2):
- H36M true-GT: standard protocol S1,S5-S8 -> train; S9,S11 -> val.
- AIST++: split by genre to avoid motion/choreography overlap.
    train genres: gBR, gHO, gJB, gJS, gKR, gLH
    val genres:   gLO, gMH, gPO, gWA
- Shelf/Campus (detected): train files -> train; val files -> val.

Output manifest is written to configs/splits/mix_true_gt_v2.yaml.
"""

from pathlib import Path
from typing import List, Tuple
import yaml

ROOT = Path(__file__).resolve().parents[1]


def h36m_splits() -> Tuple[List[Path], List[Path]]:
    train, val = [], []
    for f in sorted((ROOT / "data/h36m_true_gt").glob("*_multiview_m.npz")):
        # filename format: s_<subject>_acts_..._multiview_m.npz
        subject = f.stem.split("_")[1]
        if subject in {"09", "11"}:
            val.append(f)
        else:
            train.append(f)
    return train, val


def aist_splits() -> Tuple[List[Path], List[Path]]:
    train_genres = {"gBR", "gHO", "gJB", "gJS", "gKR", "gLH"}
    val_genres = {"gLO", "gMH", "gPO", "gWA"}
    train, val = [], []
    for f in sorted((ROOT / "data/webbridge/aistpp_canonical").glob("*_multiview.npz")):
        genre = f.stem.split("_")[0]
        if genre in val_genres:
            val.append(f)
        elif genre in train_genres:
            train.append(f)
        else:
            # If an unseen genre ever appears, include in train but warn.
            print(f"[warn] Unrecognised AIST++ genre '{genre}' for {f.name}; adding to train.")
            train.append(f)
    return train, val


def shelf_campus_splits() -> Tuple[List[Path], List[Path]]:
    train, val = [], []
    for f in sorted((ROOT / "data/webbridge/shelf_campus_detected").glob("*_m.npz")):
        if "_val_" in f.name:
            val.append(f)
        elif "_train_" in f.name:
            train.append(f)
        else:
            # fallback: sort by name prefix
            (train if f.name.startswith(("shelf_seq1_train", "campus_seq1_train")) else val).append(f)
    return train, val


def relative(files: List[Path]) -> List[str]:
    return [str(f.relative_to(ROOT)).replace("\\", "/") for f in files]


def names_for(files: List[Path], label: str) -> List[str]:
    return [label] * len(files)


def main() -> None:
    h36m_train, h36m_val = h36m_splits()
    aist_train, aist_val = aist_splits()
    sc_train, sc_val = shelf_campus_splits()

    train_files = h36m_train + aist_train + sc_train
    val_files = h36m_val + aist_val + sc_val

    manifest = {
        "name": "H36M True GT + AIST++ + Shelf/Campus mixed training (v2)",
        "description": (
            "Cross-dataset mix using non-circular H36M true-GT, AIST++ canonical multi-view clips, "
            "and detected Shelf/Campus. H36M follows the standard S1,S5-S8->S9/S11 protocol. "
            "AIST++ is split by genre to avoid choreography overlap."
        ),
        "train_paths": relative(train_files),
        "train_names": names_for(h36m_train, "h36m")
        + names_for(aist_train, "aist")
        + names_for(sc_train, "shelf_campus"),
        "val_paths": relative(val_files),
        "val_names": names_for(h36m_val, "h36m")
        + names_for(aist_val, "aist")
        + names_for(sc_val, "shelf_campus"),
    }

    out_path = ROOT / "configs/splits/mix_true_gt_v2.yaml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write("# Mixed-dataset training manifest (H36M true-GT + AIST++ + Shelf/Campus).\n")
        f.write("# Generated by scripts/generate_mix_true_gt_v2.py; do not edit by hand.\n")
        f.write("#\n")
        f.write("# H36M true-GT: non-circular mocap world coordinates from data/h36m_true_gt/.\n")
        f.write("#   Train subjects: S1, S5, S6, S7, S8\n")
        f.write("#   Val subjects:   S9, S11\n")
        f.write("# AIST++: canonical multi-view .npz under data/webbridge/aistpp_canonical/.\n")
        f.write("#   Train genres: gBR, gHO, gJB, gJS, gKR, gLH\n")
        f.write("#   Val genres:   gLO, gMH, gPO, gWA\n")
        f.write("# Shelf/Campus: detected 2D + true 3D under data/webbridge/shelf_campus_detected/.\n")
        f.write("#   Train files: *_train_detected_m.npz\n")
        f.write("#   Val files:   *_val_detected_m.npz\n")
        f.write("\n")
        yaml.dump(manifest, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    print(f"[mix_true_gt_v2] wrote {out_path}")
    print(f"  train samples: {len(train_files)} (h36m={len(h36m_train)}, aist={len(aist_train)}, sc={len(sc_train)})")
    print(f"  val   samples: {len(val_files)} (h36m={len(h36m_val)}, aist={len(aist_val)}, sc={len(sc_val)})")


if __name__ == "__main__":
    main()
