#!/usr/bin/env python3
"""Poll A800 until MPI-INF-3DHP detection + DLT baseline finish, then update docs."""

from __future__ import annotations

import json
import subprocess
import time
from pathlib import Path

REMOTE_ROOT = "/mnt/nvme0n1p1/zhangzy/motionflow-multiview-kimiswarm-iter20"
DETECTED_DIR = f"{REMOTE_ROOT}/data/webbridge/mpi_inf_3dhp_detected_2d"
DLT_JSON = f"{REMOTE_ROOT}/outputs/mpi_rtmpose_detected_2d/dlt_baseline_detected_2d.json"

LOCAL_REPO = Path(__file__).resolve().parents[1]
RESULTS_DOC = LOCAL_REPO / "docs" / "results_true_gt_h36m.md"
HANDOFF_DOC = LOCAL_REPO / "docs" / "handoff_qwen3.8max.md"


def ssh_run(cmd: str) -> str:
    return subprocess.check_output(["ssh", "a800-D", cmd], text=True).strip()


def count_files() -> int:
    try:
        out = ssh_run(f"ls {DETECTED_DIR}/*.npz 2>/dev/null | wc -l")
        return int(out)
    except subprocess.CalledProcessError:
        return 0


def fetch_dlt_json() -> dict:
    raw = ssh_run(f"cat {DLT_JSON}")
    return json.loads(raw)


def poll_until_complete() -> dict:
    print("Monitoring MPI-INF-3DHP RTMPose detection on A800 GPU 7...")
    last_count = 0
    while True:
        count = count_files()
        if count != last_count:
            print(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] {count}/16 .npz files ready")
            last_count = count
        if count >= 16:
            print("All 16 .npz files ready. Waiting for DLT baseline JSON...")
            break
        time.sleep(300)  # 5 minutes

    # Wait for the DLT baseline to complete (per_file has 16 entries)
    while True:
        try:
            data = fetch_dlt_json()
            if len(data.get("per_file", [])) >= 16:
                print(f"DLT baseline complete: mean MPJPE = {data['mean_mpjpe_mm']:.3f} mm")
                return data
        except Exception as exc:
            print(f"  DLT JSON not ready yet: {exc}")
        time.sleep(300)


def update_results_doc(mpjpe: float, pa_mpjpe: float) -> None:
    text = RESULTS_DOC.read_text(encoding="utf-8")

    # Replace the MPI-INF-3DHP DLT baseline table rows
    old_block = (
        "| Status | Files ready | DLT MPJPE (mm) | PA-MPJPE (mm) | Notes |\n"
        "|---|---:|---:|---:|---|\n"
        "| Partial | 4 / 16 | **150.50** | **164.22** | Mean over the first two completed files (`s_01_seq_01_02_v14_multiview_m.npz` 138.31 mm, `s_01_seq_01_v14_multiview_m.npz` 162.69 mm); not representative. Full MPI DLT pending remaining files. |\n"
        "| Full | pending | — | — | Pending completion of RTMPose detection for all sequences. |"
    )
    new_block = (
        f"| Status | Files ready | DLT MPJPE (mm) | PA-MPJPE (mm) | Notes |\n"
        "|---|---:|---:|---:|---|\n"
        f"| **Full** | **16 / 16** | **{mpjpe:.3f}** | **{pa_mpjpe:.3f}** | RTMPose detected-2D, confidence-weighted DLT over all MPI-INF-3DHP test sequences. |"
    )

    if old_block not in text:
        raise RuntimeError("Could not find expected MPI DLT baseline table block in results doc")

    text = text.replace(old_block, new_block)

    # Update the in-flight paragraph if still present
    old_para = (
        "**MPI-INF-3DHP DLT baseline** is in progress. Four of 16 expected detected-2D files have been generated; the mean DLT on the first two files is **150.50 mm** / PA-MPJPE **164.22 mm**, which is not representative. Full MPI DLT results are pending."
    )
    new_para = (
        f"**MPI-INF-3DHP DLT baseline** is complete. All 16 detected-2D files were generated, and the confidence-weighted DLT baseline reports **{mpjpe:.3f} mm** MPJPE / **{pa_mpjpe:.3f} mm** PA-MPJPE."
    )
    text = text.replace(old_para, new_para)

    # Update last updated line
    old_updated = "Last updated: **2026-08-11 22:50 UTC** (v25 stability var-view completed; Iskakov baseline launched on GPU 4; AIST++-only fast v2 and v25 mixed-dataset stability training on GPU 5/6; MPI RTMPose 6/16; sparse-view wrapper fix applied)."
    new_updated = f"Last updated: **{time.strftime('%Y-%m-%d %H:%M UTC')}** (MPI-INF-3DHP RTMPose detection finished; DLT baseline recorded)."
    text = text.replace(old_updated, new_updated)

    RESULTS_DOC.write_text(text, encoding="utf-8")
    print(f"Updated {RESULTS_DOC}")


def update_handoff_doc(mpjpe: float, pa_mpjpe: float) -> None:
    timestamp = time.strftime("%Y-%m-%d %H:%M UTC")
    if HANDOFF_DOC.exists():
        content = HANDOFF_DOC.read_text(encoding="utf-8")
    else:
        content = "# Handoff for qwen3.8max\n\n"

    section = f"\n## MPI-INF-3DHP DLT baseline ({timestamp})\n\n"
    section += f"- Status: **complete**\n"
    section += f"- Files: **16/16** detected-2D `.npz` files generated by RTMPose on A800 GPU 7\n"
    section += f"- DLT MPJPE: **{mpjpe:.3f} mm**\n"
    section += f"- DLT PA-MPJPE: **{pa_mpjpe:.3f} mm**\n"
    section += f"- Source JSON (A800): `{DLT_JSON}`\n"
    section += f"- Updated docs: `docs/results_true_gt_h36m.md`\n"

    content += section
    HANDOFF_DOC.write_text(content, encoding="utf-8")
    print(f"Updated {HANDOFF_DOC}")


def main() -> int:
    data = poll_until_complete()
    mpjpe = float(data["mean_mpjpe_mm"])
    pa_mpjpe = float(data["mean_pa_mpjpe_mm"])

    update_results_doc(mpjpe, pa_mpjpe)
    update_handoff_doc(mpjpe, pa_mpjpe)

    print("\nMPI-INF-3DHP DLT baseline recording complete.")
    print(f"  mean MPJPE:    {mpjpe:.3f} mm")
    print(f"  mean PA-MPJPE: {pa_mpjpe:.3f} mm")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
