name: WebBridge H36M + MPI-INF-3DHP Mixed (17 joints, 14 views padded)
train_paths:
  - data/webbridge/h36m_meters/s_01_acts_02_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_03_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_04_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_05_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_06_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_07_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_08_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_09_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_10_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_11_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_12_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_13_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_14_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_15_multiview_m.npz
  - data/webbridge/h36m_meters/s_01_acts_16_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_01_seq_01_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_01_seq_02_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_03_seq_01_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_03_seq_02_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_04_seq_01_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_04_seq_02_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_05_seq_01_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_05_seq_02_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_06_seq_01_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_06_seq_02_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_07_seq_01_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_07_seq_02_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_08_seq_01_v14_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_08_seq_02_v14_multiview_m.npz
train_names:
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - mpi
  - mpi
  - mpi
  - mpi
  - mpi
  - mpi
  - mpi
  - mpi
  - mpi
  - mpi
  - mpi
  - mpi
  - mpi
  - mpi
val_paths:
  - data/webbridge/h36m_meters/s_09_acts_02_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_03_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_04_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_05_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_06_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_07_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_08_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_09_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_10_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_11_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_12_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_13_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_14_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_15_multiview_m.npz
  - data/webbridge/h36m_meters/s_09_acts_16_multiview_m.npz
  - data/webbridge/mpi_inf_3dhp/s_02_seq_01_v14_multiview_m.npz
val_names:
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - h36m
  - mpi
